import {
  DEFAULT_LICENSE_NOTE,
  type CourseDetail,
  type CourseMeta,
} from '../../contracts'
import { analysisWork, moduleOf, readingWork } from '../scaffold'

export const machineLearningMeta: CourseMeta = {
  id: 'machine-learning',
  title: 'Machine Learning',
  status: 'partial',
  track: 'Core / strong elective',
  level: 'undergraduate+graduate',
  moduleCount: 8,
  liveLabCount: 0,
  academicNote: 'Statistical learning · distinct from classical AI',
  blurb:
    'Supervised learning, generalization, linear models, features, evaluation, and unsupervised/RL landscape — undergrad ML depth.',
  cs2023Areas: ['AI'],
}

export const machineLearningCourse: CourseDetail = {
  ...machineLearningMeta,
  peerAnchors: [
    {
      school: 'MIT',
      courseCode: '6.036',
      title: 'Introduction to Machine Learning',
      note: 'Undergrad ML gateway',
    },
    {
      school: 'Stanford',
      courseCode: 'CS229',
      title: 'Machine Learning',
      url: 'https://cs229.stanford.edu/',
      note: 'Canonical ML course materials (public notes vary by year)',
    },
    {
      school: 'CMU',
      courseCode: '10-301/601',
      title: 'Introduction to Machine Learning',
      note: 'Undergrad/grad intro ML',
    },
  ],
  licenseNote: DEFAULT_LICENSE_NOTE,
  cs2023Areas: ['AI'],
  overview: `**Machine Learning** is the statistical learning course: generalization, linear models, features, model selection, and evaluation. It is **separate from Artificial Intelligence** (search/knowledge/agents).

Browser labs will be **toy but rigorous** (decision boundaries, train/test curves)—not GPU training or production MLOps. Math prerequisites are real; set expectations accordingly.`,
  prerequisites: [
    'Linear algebra (vectors, matrices, projections)',
    'Calculus (gradients, partial derivatives)',
    'Probability & statistics intro (Discrete Math M7 or equivalent)',
    'Python for numerical homework offline',
  ],
  learningGoals: [
    'Frame supervised learning problems with features, loss, and hypothesis class',
    'Analyze train vs test error and diagnose over/underfitting',
    'Derive and implement (offline) gradient-based linear models',
    'Select evaluation metrics appropriate to the task',
    'Map unsupervised and RL landscapes at survey depth',
  ],
  modules: [
    moduleOf({
      id: 'ml-m1',
      code: 'M1',
      title: 'Learning problem & generalization',
      schedule: 'Week 1',
      summary: 'Supervised learning setup; train/test; inductive bias.',
      topics: ['Supervised learning setup', 'Hypothesis class', 'Train/test split', 'Generalization gap', 'Inductive bias'],
      outcomes: [
        'Define a learning problem with features, labels, and loss',
        'Explain why train accuracy alone is not success',
      ],
      lectureBeats: [
        'Supervised learning setup: X, Y, hypothesis class, loss',
        'Train vs test split and the generalization gap',
        'Underfit ↔ sweet spot ↔ overfit on capacity curves',
        'Inductive bias of linear models vs trees',
        'ML course is statistical learning — not classical AI search',
      ],
      readings: [
        { label: 'Hastie/Tibshirani/Friedman ESL or ISL — intro chapters', kind: 'textbook' },
        { label: 'Stanford CS229 notes — introduction (public)', kind: 'curriculum', url: 'https://cs229.stanford.edu/' },
      ],
      work: [
        analysisWork(
          'ml-m1-ps',
          'Problem set: generalization',
          'Diagnose over/underfit scenarios from learning curves sketches.',
          'Written. No “download this private dataset” requirement.',
          'partial',
        ),
        {
          id: 'ml-m1-lab-curves',
          title: 'Lab: train vs test curves',
          kind: 'lab',
          status: 'live',
          labId: 'ml',
          objective: 'Step the capacity cartoon; identify underfit / sweet spot / overfit regions.',
          brief: 'mlDemo train-test-curves. Record k at minimum test error. Relate to bias-variance language.',
          config: { mlDemo: 'train-test-curves' },
          sources: [{ label: 'ISL intro / CS229', kind: 'curriculum', url: 'https://cs229.stanford.edu/' }],
        },
      ],
    }),
    moduleOf({
      id: 'ml-m2',
      code: 'M2',
      title: 'Linear regression & least squares',
      schedule: 'Weeks 2–3',
      summary: 'Squared loss, normal equations landscape, gradient descent.',
      topics: ['Linear models', 'Squared loss', 'Normal equations idea', 'Gradient descent', 'Feature scaling', 'Polynomial features'],
      outcomes: [
        'Derive gradients for squared loss linear regression',
        'Explain when closed form vs iterative methods apply',
      ],
      lectureBeats: [
        'Linear model and squared loss; geometry of least squares',
        'Normal equations idea vs gradient descent',
        'Learning rate, scaling, and polynomial features',
        'One full GD step by hand on a tiny dataset',
        'Lab: linreg-1d watches m,b over epochs',
      ],
      readings: [
        { label: 'CS229 notes — supervised learning / linear regression', kind: 'curriculum', url: 'https://cs229.stanford.edu/' },
        { label: 'ISL — linear regression chapters', kind: 'textbook' },
      ],
      work: [
        analysisWork(
          'ml-m2-ps',
          'Problem set: linear regression',
          'Hand calculations on tiny datasets; gradient steps; feature transforms.',
          'Written + optional offline notebook.',
          'partial',
        ),
        {
          id: 'ml-m2-lab',
          title: 'Lab: linear regression GD toy',
          kind: 'lab',
          status: 'live',
          labId: 'ml',
          objective: 'Step gradient descent on a 1D least-squares toy; watch m,b converge.',
          brief:
            'Client-side toy only — not production training. Record m,b over epochs; relate to squared loss.',
          config: { mlDemo: 'linreg-1d' },
          sources: [{ label: 'CS229 notes — linear regression', kind: 'curriculum', url: 'https://cs229.stanford.edu/' }],
        },
      ],
    }),
    moduleOf({
      id: 'ml-m3',
      code: 'M3',
      title: 'Classification & logistic regression',
      schedule: 'Weeks 4–5',
      summary: 'Decision boundaries, logistic loss, and multiclass landscape.',
      topics: ['Decision boundaries', 'Logistic regression', 'Cross-entropy', 'Softmax landscape', 'Class imbalance intro'],
      outcomes: [
        'Derive logistic regression gradient steps at course depth',
        'Interpret probabilities vs hard labels carefully',
      ],
      lectureBeats: [
        'Decision boundaries: sign(w·x+b) geometry',
        'Logistic regression and cross-entropy intuition',
        'Precision, recall, and class imbalance intro',
        'Softmax multiclass landscape',
        'Lab: perceptron / boundary on a 2D toy set',
      ],
      readings: [{ label: 'CS229 / ISL — classification', kind: 'curriculum' }],
      work: [
        analysisWork(
          'ml-m3-ps',
          'Problem set: classification',
          'Boundary geometry problems and logistic likelihood reasoning.',
          'Written.',
          'partial',
        ),
        {
          id: 'ml-m3-lab',
          title: 'Lab: perceptron decision boundary',
          kind: 'lab',
          status: 'live',
          labId: 'ml',
          objective: 'Watch a linear boundary update on a 2D toy binary set.',
          brief: 'Step the perceptron demo; sketch the final boundary; discuss linear separability.',
          config: { mlDemo: 'decision-boundary' },
          sources: [{ label: 'CS229 / ISL — classification', kind: 'curriculum' }],
        },
      ],
    }),
    moduleOf({
      id: 'ml-m4',
      code: 'M4',
      title: 'Features, kernels landscape & bias-variance',
      schedule: 'Week 6',
      summary: 'Feature engineering, capacity, and bias-variance trade-off.',
      topics: ['Feature maps', 'Bias-variance', 'Regularization (L2/L1 idea)', 'Kernels landscape', 'RBF intuition'],
      outcomes: [
        'Connect model capacity to generalization curves',
        'Choose regularization intent for a scenario',
      ],
      lectureBeats: [
        'Feature maps and model capacity',
        'Bias–variance trade-off (qualitative + curves)',
        'L2/L1 regularization intent; feature scaling',
        'Kernels / RBF landscape without full RKHS',
        'Choosing λ and features with validation, not test',
      ],
      readings: [{ label: 'ISL/ESL — bias-variance & regularization', kind: 'textbook' }],
      work: [
        analysisWork(
          'ml-m4-ps',
          'Problem set: capacity & regularization',
          'Interpret curves; propose feature/regularization changes with rationale.',
          'Written.',
          'partial',
        ),
      ],
    }),
    moduleOf({
      id: 'ml-m5',
      code: 'M5',
      title: 'Model selection & evaluation',
      schedule: 'Week 7',
      summary: 'Cross-validation, metrics, and leakage pitfalls.',
      topics: ['Cross-validation', 'Precision/recall/F1', 'ROC/AUC idea', 'Calibration intro', 'Data leakage', 'Train/val/test hygiene'],
      outcomes: [
        'Select metrics for imbalanced and ranking-style tasks',
        'Identify leakage in flawed experimental plans',
      ],
      lectureBeats: [
        'Train / validation / test hygiene',
        'k-fold cross-validation; never tune on test',
        'Precision, recall, F1, ROC/AUC idea',
        'Data leakage case studies (normalize-then-split)',
        'Imbalance: accuracy can lie; pick metrics for the cost',
      ],
      readings: [{ label: 'ISL — resampling & model assessment', kind: 'textbook' }],
      work: [
        analysisWork(
          'ml-m5-ps',
          'Problem set: evaluation design',
          'Critique experimental designs; pick metrics; spot leakage.',
          'Written case set.',
          'partial',
        ),
      ],
    }),
    moduleOf({
      id: 'ml-m6',
      code: 'M6',
      title: 'Trees, ensembles & nonparametric landscape',
      schedule: 'Weeks 8–9',
      summary: 'Decision trees, bagging/boosting idea, k-NN.',
      topics: ['Decision trees', 'Overfitting trees', 'Bagging/random forests idea', 'Boosting landscape', 'k-NN'],
      outcomes: [
        'Build small decision trees by hand',
        'Explain why ensembles reduce variance (intuition)',
      ],
      lectureBeats: [
        'Decision trees: splits, impurity, depth vs overfit',
        'Hand-build a depth-2 tree on a tiny table',
        'Bagging and random forests (variance reduction)',
        'Boosting landscape in one slide',
        'k-NN decision regions and distance choice',
      ],
      readings: [{ label: 'ISL — tree-based methods', kind: 'textbook' }],
      work: [
        analysisWork(
          'ml-m6-ps',
          'Problem set: trees & neighbors',
          'Hand-build trees; k-NN decision regions on toy points.',
          'Written.',
          'partial',
        ),
      ],
    }),
    moduleOf({
      id: 'ml-m7',
      code: 'M7',
      title: 'Neural nets intro (undergrad slice)',
      schedule: 'Weeks 10–11',
      summary: 'MLPs, backprop idea, and deep learning landscape without GPU drama.',
      topics: ['Perceptron/MLP', 'Activation functions', 'Backprop idea', 'Overfit deep models', 'What this course will not claim'],
      outcomes: [
        'Compute forward/backprop on a tiny network by hand',
        'State compute/data requirements honestly for modern DL',
      ],
      lectureBeats: [
        'MLP: layers, activations (ReLU, sigmoid)',
        'Forward pass numerics on a 2-layer toy',
        'Backprop as chain rule on a computation graph',
        'Overfitting deep models; regularization pointers',
        'Honesty: browser toys ≠ ImageNet training',
      ],
      readings: [
        { label: 'CS229 / deep learning primers (public notes)', kind: 'curriculum' },
        { label: 'Cross-link: not a full deep learning specialization', kind: 'notes' },
      ],
      work: [
        analysisWork(
          'ml-m7-ps',
          'Problem set: tiny nets',
          'Forward and backward passes on 2-layer toy nets.',
          'Written numerical problems.',
          'partial',
        ),
      ],
    }),
    moduleOf({
      id: 'ml-m8',
      code: 'M8',
      title: 'Unsupervised learning & RL landscape',
      schedule: 'Week 12',
      summary: 'Clustering, dimensionality reduction, and RL pointer back to AI.',
      topics: ['k-means', 'PCA idea', 'Mixture models landscape', 'RL/MDP pointer', 'Ethics & dataset bias intro'],
      outcomes: [
        'Run k-means reasoning on small sets',
        'Connect RL back to AI M8 MDPs without conflating courses',
      ],
      lectureBeats: [
        'Unsupervised vs supervised: no labels',
        'k-means: assign / update; init and k sensitivity',
        'PCA idea at survey depth',
        'RL/MDP pointer back to AI M8 — do not merge courses',
        'Ethics, dataset bias, and public system critique',
      ],
      readings: [
        { label: 'ISL — unsupervised chapters', kind: 'textbook' },
        { label: 'Cross-link: Artificial Intelligence M8', kind: 'notes' },
      ],
      work: [
        readingWork(
          'ml-m8-reading',
          'Case study: ML system critique',
          'Critique a public ML system write-up: data, metrics, failure modes, and ethical risks.',
          'Cite sources. Prefer public tech reports; no proprietary datasets required.',
          'partial',
        ),
        {
          id: 'ml-m8-lab-kmeans',
          title: 'Lab: k-means toy clusters',
          kind: 'lab',
          status: 'live',
          labId: 'ml',
          objective: 'Step assign/update for k=2 on a fixed 2D set; note centroid motion.',
          brief: 'Unsupervised landscape lab. Compare to supervised boundary lab from M3.',
          config: { mlDemo: 'kmeans-2d' },
          sources: [{ label: 'ISL — unsupervised chapters', kind: 'textbook' }],
        },
      ],
    }),
  ],
}
