import {
  DEFAULT_LICENSE_NOTE,
  type CourseDetail,
  type CourseMeta,
} from '../../contracts'
import { analysisHandout } from '../handouts'
import { analysisWork, moduleOf, readingWork } from '../scaffold'

export const operatingSystemsMeta: CourseMeta = {
  id: 'operating-systems',
  title: 'Operating Systems',
  status: 'partial',
  track: 'Core · required',
  level: 'undergraduate+graduate',
  moduleCount: 8,
  liveLabCount: 4,
  academicNote: 'Core systems · often junior',
  blurb:
    'Processes, concurrency, scheduling, virtual memory, file systems, and synchronization — OS as a resource manager and abstraction layer.',
  cs2023Areas: ['OS', 'PDC'],
}

export const operatingSystemsCourse: CourseDetail = {
  ...operatingSystemsMeta,
  peerAnchors: [
    {
      school: 'Stanford',
      courseCode: 'CS111',
      title: 'Operating Systems Principles',
      note: 'Modern OS principles sequence',
    },
    {
      school: 'MIT',
      courseCode: '6.828',
      title: 'Operating System Engineering',
      url: 'https://pdos.csail.mit.edu/6.828/',
      note: 'Advanced / grad-leaning; xv6 tradition',
    },
    {
      school: 'Berkeley',
      courseCode: 'CS 162',
      title: 'Operating Systems and Systems Programming',
      note: 'Classic undergrad OS',
    },
  ],
  licenseNote: DEFAULT_LICENSE_NOTE,
  cs2023Areas: ['OS', 'PDC'],
  overview: `**Operating Systems** studies how the kernel multiplexes hardware: processes and threads, CPU scheduling, synchronization, virtual memory, and file systems.

Prereq systems exposure (Computer Systems / CSAPP-style) is strongly recommended. Full kernel projects (xv6/Pintos-style) are **not** shipped in-browser; this course publishes a university-aligned module plan with written work now and progressive instruments later.`,
  prerequisites: [
    'Computer Systems (or equivalent: C, assembly, memory, exceptions)',
    'Data Structures',
    'Comfort with concurrency puzzles at puzzle level',
  ],
  learningGoals: [
    'Explain process/thread abstractions and context switching',
    'Reason about race conditions and use locks/semaphores correctly on small problems',
    'Compare scheduling policies with fairness/latency trade-offs',
    'Describe paging, replacement, and thrashing at course depth',
    'Outline file-system layout and crash-consistency ideas',
  ],
  modules: [
    moduleOf({
      id: 'os-m1',
      code: 'M1',
      title: 'OS role & architectural overview',
      schedule: 'Week 1',
      summary: 'Why kernels exist: protection, multiplexing, and abstractions.',
      topics: ['Dual mode', 'System calls', 'Kernel vs user', 'Monolithic vs microkernel landscape', 'Boot sketch'],
      outcomes: [
        'Explain protection boundaries and the syscall path',
        'Map OS abstractions to hardware mechanisms',
      ],
      lectureBeats: [
        'Dual mode + MMU: user code cannot touch device regs or page tables directly',
        'Syscall = controlled trap into kernel with validated args',
        'OS multiplexes CPU, memory, and devices behind process/file abstractions',
        'Monolithic vs microkernel: reliability vs path-length trade-offs at survey depth',
      ],
      readings: [
        { label: 'OSTEP — intro chapters (free)', kind: 'textbook', url: 'https://ostep.org/' },
        { label: 'Anderson/Dahlin or Tanenbaum — selected intro', kind: 'textbook' },
      ],
      work: [
        analysisWork(
          'os-m1-ps',
          'Problem set: OS abstractions',
          'Map user-facing APIs to kernel mechanisms on short scenarios.',
          'Written; cite OSTEP or equivalent.',
          'partial',
        ),
      ],
    }),
    moduleOf({
      id: 'os-m2',
      code: 'M2',
      title: 'Processes & address spaces',
      schedule: 'Weeks 2–3',
      summary: 'Process lifecycle, address spaces, and isolation.',
      topics: ['PCB / process states', 'fork/exec idea', 'Address space layout', 'IPC overview'],
      outcomes: [
        'Trace process creation and image loading at conceptual level',
        'Explain isolation benefits and costs',
      ],
      lectureBeats: [
        'States: new → ready → running ⇄ blocked → terminated',
        'fork copies address space (COW common); exec loads a new image',
        'Isolation benefits vs IPC/copy costs',
        'Lab: process-lifecycle steps A and B through I/O block and exit',
      ],
      readings: [{ label: 'OSTEP — processes & address spaces', kind: 'textbook', url: 'https://ostep.org/' }],
      work: [
        analysisWork(
          'os-m2-ps',
          'Problem set: processes',
          'Reason about fork/exec diagrams and address-space snapshots.',
          'Written. No proprietary lab binaries.',
          'partial',
        ),
        {
          id: 'os-m2-lab',
          title: 'Lab: process state machine',
          kind: 'lab',
          status: 'live',
          labId: 'systems',
          objective: 'Step two processes through new/ready/running/blocked/terminated.',
          brief:
            'Use the process lifecycle demo. Trace each transition and name the scheduler or I/O event that causes it.',
          config: { systemsDemo: 'process-lifecycle' },
          sources: [{ label: 'OSTEP — processes', kind: 'textbook', url: 'https://ostep.org/' }],
        },
      ],
    }),
    moduleOf({
      id: 'os-m3',
      code: 'M3',
      title: 'CPU scheduling',
      schedule: 'Week 4',
      summary: 'Policies for multiplexing the CPU under different goals.',
      topics: ['FCFS, SJF, RR', 'Priority & aging', 'Multilevel feedback idea', 'Metrics: turnaround, response, fairness'],
      outcomes: [
        'Compute simple schedules by hand for small job sets',
        'Argue when RR vs SJF-like policies fit workload goals',
      ],
      lectureBeats: [
        'Metrics: turnaround, waiting, response; no free lunch across workloads',
        'FCFS convoy effect; SJF optimal average waiting (non-preemptive, known bursts)',
        'RR quantum trades switches vs fairness; q→∞ becomes FCFS',
        'Labs use a fixed 4-job instance so policies are comparable',
      ],
      readings: [{ label: 'OSTEP — scheduling', kind: 'textbook', url: 'https://ostep.org/' }],
      work: [
        analysisWork(
          'os-m3-ps',
          'Problem set: scheduling',
          'Hand-simulate schedules and compare metrics across policies.',
          'Written quantitative problems.',
          'partial',
        ),
        {
          id: 'os-m3-lab-fcfs',
          title: 'Lab: FCFS scheduling',
          kind: 'lab',
          status: 'live',
          labId: 'systems',
          objective: 'Trace FCFS on the fixed 4-job instance; record makespan and finish order.',
          brief: 'Run the FCFS demo only. Then open SJF and RR labs for the same jobs to compare.',
          config: { systemsDemo: 'schedule-fcfs' },
          sources: [{ label: 'OSTEP — scheduling', kind: 'textbook', url: 'https://ostep.org/' }],
        },
        {
          id: 'os-m3-lab-sjf',
          title: 'Lab: SJF scheduling',
          kind: 'lab',
          status: 'live',
          labId: 'systems',
          objective: 'Trace non-preemptive SJF on the same 4-job instance as FCFS.',
          brief: 'Compare finish order and waiting intuition against FCFS.',
          config: { systemsDemo: 'schedule-sjf' },
          sources: [{ label: 'OSTEP — scheduling', kind: 'textbook', url: 'https://ostep.org/' }],
        },
        {
          id: 'os-m3-lab-rr',
          title: 'Lab: Round-Robin scheduling',
          kind: 'lab',
          status: 'live',
          labId: 'systems',
          objective: 'Trace RR (q=2) on the same 4-job instance; note preemption slices.',
          brief: 'Tabulate slices; discuss response-time vs FCFS/SJF for short jobs.',
          config: { systemsDemo: 'schedule-rr' },
          sources: [{ label: 'OSTEP — scheduling', kind: 'textbook', url: 'https://ostep.org/' }],
        },
      ],
    }),
    moduleOf({
      id: 'os-m4',
      code: 'M4',
      title: 'Concurrency & synchronization',
      schedule: 'Weeks 5–7',
      summary: 'Threads, races, locks, condition variables, and classic bugs.',
      topics: ['Threads vs processes', 'Critical sections', 'Mutexes', 'Semaphores / CVs', 'Deadlock', 'Livelock & priority inversion (survey)'],
      outcomes: [
        'Identify races and propose correct synchronization',
        'Apply lock ordering or other deadlock avoidance on small examples',
      ],
      lectureBeats: [
        'Race: concurrent shared updates without atomic critical sections',
        'Mutex + CVs (or semaphores) for bounded buffer; state invariants matter',
        'Deadlock needs circular wait; lock ordering is a simple prevention',
        'Threads share address space; processes isolate — different failure modes',
      ],
      readings: [
        { label: 'OSTEP — concurrency chapters', kind: 'textbook', url: 'https://ostep.org/' },
        { label: 'Berkeley CS 162 — synchronization unit', kind: 'curriculum' },
      ],
      work: [
        {
          ...analysisWork(
            'os-m4-ps',
            'Problem set: synchronization',
            'Fix or prove incorrect concurrent snippets; solve bounded-buffer style problems.',
            'Written concurrency puzzles (not proprietary autograders / not Pintos/xv6 dumps).',
            'live',
            [{ label: 'OSTEP — concurrency', kind: 'textbook', url: 'https://ostep.org/' }],
          ),
          handout: analysisHandout(
            [
              'Identify the race in a 10-line shared-counter sketch; propose a lock placement.',
              'Bounded buffer: write wait/signal pseudocode; argue no deadlock under your locking order.',
              'Give a lock-order deadlock example (2 locks) and a fix.',
            ],
            { timeEstimate: '75–100 min' },
          ),
        },
      ],
    }),
    moduleOf({
      id: 'os-m5',
      code: 'M5',
      title: 'Virtual memory & paging',
      schedule: 'Weeks 8–9',
      summary: 'Page tables, TLBs, replacement policies, and thrashing.',
      topics: ['Paging hardware', 'Multi-level page tables', 'TLB', 'Replacement (LRU/clock)', 'Working sets & thrashing'],
      outcomes: [
        'Simulate simple page replacement on a reference string',
        'Explain thrashing and mitigation strategies',
      ],
      lectureBeats: [
        'Paging + multi-level tables + TLB form the translation path',
        'FIFO vs LRU on the shared ref string 1,2,3,2,4,1,5,2,1,3 (3 frames)',
        'Thrashing: working set exceeds frames → mostly faulting',
        'Labs: page-fifo and page-lru for direct policy comparison',
      ],
      readings: [{ label: 'OSTEP — virtual memory', kind: 'textbook', url: 'https://ostep.org/' }],
      work: [
        analysisWork(
          'os-m5-ps',
          'Problem set: paging & replacement',
          'Work translation and replacement simulations; discuss thrashing cases.',
          'Written.',
          'partial',
        ),
        {
          id: 'os-m5-lab-fifo',
          title: 'Lab: FIFO page replacement',
          kind: 'lab',
          status: 'live',
          labId: 'systems',
          objective: 'Count page faults under FIFO (3 frames) on the shared reference string.',
          brief: 'Run FIFO end-to-end; record fault count. Pair with the LRU lab for comparison.',
          config: { systemsDemo: 'page-fifo' },
          sources: [{ label: 'OSTEP — virtual memory / replacement', kind: 'textbook', url: 'https://ostep.org/' }],
        },
        {
          id: 'os-m5-lab-lru',
          title: 'Lab: LRU page replacement',
          kind: 'lab',
          status: 'live',
          labId: 'systems',
          objective: 'Count page faults under LRU on the same reference string as FIFO.',
          brief: 'Tabulate FIFO vs LRU faults; explain one differing hit/miss.',
          config: { systemsDemo: 'page-lru' },
          sources: [{ label: 'OSTEP — virtual memory / replacement', kind: 'textbook', url: 'https://ostep.org/' }],
        },
      ],
    }),
    moduleOf({
      id: 'os-m6',
      code: 'M6',
      title: 'File systems',
      schedule: 'Weeks 10–11',
      summary: 'Files, directories, allocation, and crash consistency ideas.',
      topics: ['File abstraction', 'Directories', 'Inode/FAT/extent ideas', 'Journaling overview', 'FSCK idea'],
      outcomes: [
        'Compare allocation strategies and directory designs',
        'Explain why crash consistency needs careful update protocols',
      ],
      lectureBeats: [
        'File = named bytes; inode holds metadata and block pointers / extents',
        'Directories map names → inode numbers; path walk is recursive lookup',
        'Allocation: contiguous vs linked/FAT vs indexed — fragmentation trade-offs',
        'Crash consistency: ordered updates, journaling, or fsck recovery ideas',
      ],
      readings: [{ label: 'OSTEP — file systems', kind: 'textbook', url: 'https://ostep.org/' }],
      work: [
        analysisWork(
          'os-m6-ps',
          'Problem set: file systems',
          'Reason about layout, free space, and failure scenarios on simplified FS models.',
          'Written.',
          'partial',
        ),
      ],
    }),
    moduleOf({
      id: 'os-m7',
      code: 'M7',
      title: 'I/O, devices & storage stack',
      schedule: 'Week 12',
      summary: 'Device drivers landscape, disks/SSDs, and I/O scheduling ideas.',
      topics: ['Device interfaces', 'Interrupts vs polling', 'Disk geometry (legacy)', 'SSD traits', 'I/O schedulers overview'],
      outcomes: [
        'Place storage devices in the OS stack',
        'Compare latency/throughput trade-offs qualitatively',
      ],
      lectureBeats: [
        'I/O path: user buffer → kernel → block layer → device driver → hardware',
        'Interrupts vs polling: latency vs overhead at high event rates',
        'HDD seeks vs SSD random reads; scheduler goals differ by medium',
        'Place devices under VFS/block abstractions the FS module already used',
      ],
      readings: [{ label: 'OSTEP — I/O & devices selected', kind: 'textbook', url: 'https://ostep.org/' }],
      work: [
        analysisWork(
          'os-m7-ps',
          'Problem set: I/O stack',
          'Trace a read from application buffer to device and back.',
          'Written systems narrative with diagrams.',
          'partial',
        ),
      ],
    }),
    moduleOf({
      id: 'os-m8',
      code: 'M8',
      title: 'Security, isolation & advanced topics',
      schedule: 'Week 13',
      summary: 'Protection, least privilege, and survey of containers/VMs.',
      topics: ['Access control ideas', 'Capabilities overview', 'Sandboxing', 'VMs vs containers (survey)', 'Course synthesis'],
      outcomes: [
        'State isolation mechanisms the OS provides',
        'Map one modern isolation tech to classic OS concepts',
      ],
      lectureBeats: [
        'Least privilege: processes, UIDs, capabilities, and sandbox policies',
        'VMs virtualize hardware; containers share a kernel with namespaces/cgroups',
        'Map modern isolation onto process + VM abstractions from earlier modules',
        'Course synthesis: protection, multiplexing, and abstractions as one story',
      ],
      readings: [
        { label: 'OSTEP / OS security survey chapters', kind: 'textbook' },
        { label: 'MIT 6.828 advanced materials (selected public)', kind: 'curriculum', url: 'https://pdos.csail.mit.edu/6.828/' },
      ],
      work: [
        readingWork(
          'os-m8-reading',
          'Reading: isolation case study',
          'Write a one-page map of containers or VMs onto process/VM abstractions from earlier modules.',
          'Cite public sources; no proprietary lab content.',
          'partial',
        ),
      ],
    }),
  ],
}
