/**
 * Emit CONTENT_BACKLOG.md from current catalog + meat registry.
 * Run: node --experimental-strip-types scripts/emit-backlog.mjs
 * (Uses vitest path via dynamic import of built logic — simpler: parse via test dump)
 */
import { writeFileSync } from 'node:fs'
import { pathToFileURL } from 'node:url'
import { createRequire } from 'node:module'

// Fallback: run vitest programmatically is heavy; this script documents the factory.
// Real backlog is asserted by completeness.test.ts.

const note = `# Content backlog (factory)

Generated by factory Wave 0. Authoritative missing list comes from:

\`\`\`
npx vitest run src/content/packs/completeness.test.ts
\`\`\`

## Ownership (single-writer)

| File | Courses |
|------|---------|
| algorithms-meat.ts | algorithms |
| ds-meat.ts | data-structures |
| systems-os-meat.ts | computer-systems, operating-systems |
| math-ai-ml-meat.ts | discrete-math, theory-of-computation, artificial-intelligence, machine-learning |
| other-meat.ts | databases, computer-networks, programming-languages, software-engineering + labMeat |

## Quality

See \`src/content/packs/QUALITY.md\`.

## Wave targets

- W1: algorithms 100% meat + beats
- W2: all other courses 100% meat
- W3: all modules ≥4 lectureBeats
- W4: completeness CI green + full suite
`

writeFileSync(new URL('../docs/CONTENT_BACKLOG.md', import.meta.url), note)
console.log('Wrote docs/CONTENT_BACKLOG.md')
